name: Weekly Wordlist Update

on:
  schedule:
    # Runs every week on Monday at 00:00 UTC
    - cron: '0 0 * * MON'

jobs:
  update-wordlist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download best-dns-wordlist.txt
      run: curl -o best-dns-wordlist.txt https://wordlists-cdn.assetnote.io/data/manual/best-dns-wordlist.txt

    - name: Download all.txt
      run: curl -o all.txt https://gist.githubusercontent.com/jhaddix/86a06c5dc309d08580a018c66354a056/raw/96f4e51d96b2203f19f6381c8c545b278eaa0837/all.txt

    - name: Combine, sort, and uniq files
      run: |
        cat best-dns-wordlist.txt all.txt | sort | uniq > final-wordlist.txt

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add final-wordlist.txt
        git commit -m 'Update wordlist'
        git push
